name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "iPhone XR Restore ipsw"
  comment: "iOS 14.3 ipsw for XR restore"
  url: "http://updates-http.cdn-apple.com/2020WinterFCS/fullrestores/001-87267/C892DBD9-83E0-4538-95A8-5E9E45C4F095/iPhone11,8,iPhone12,1_14.3_18C66_Restore.ipsw"
  file_name: "iPhone11,8,iPhone12,1_14.3_18C66_Restore.ipsw"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
